### ISSUE TITLE
Eliminar usuario administrador

### ISSUE THREAD

**Issue by oswaldoguevara** [davidrochin/sae-ingles#1]
Un administrador no puede eliminar otro administrador aunque tenga la opción de eliminarlo

**Comment by davidrochin** [comment]
Ya checaste si solo es de Administrador a Administrador? Se me hace que lo de eliminar usuarios ni siquiera está hecho en lo absoluto. Osea que nadie puede eliminar a nadie, porque no hay código para eso.

**Comment by oswaldoguevara** [comment]
no se eliminará solo se podra desactivar ya que los usuarios tendran acciones en el sistema que no se deben eliminar
