### ISSUE TITLE
Identificar alumnos internos a externos

### ISSUE THREAD

**Issue by oswaldoguevara** [davidrochin/sae-ingles#11]
El sistema generara los números de control o ID de los alumnos externos, se solicitó que siguiera el formato de los alumnos internos solo que cambiara con letras o dos dígitos diferentes a los internos.
Mientras que los alumnos internos al ingresarlos al sistema su numero de control se ingresará manual.
Ej.
Int: 14 44 06 00
Ext: 14 00 06 00  <-- recomendable
Ext: 14 EX 06 00

**Comment by davidrochin** [comment]
Yo no recomiendo hacerlo de esta manera ya que va a dificultar las tareas como "Filtrame, ordename, o formateame los numeros de control". En caso de que sea muy necesario, recomiento que sea añadiendo el prefijo "EX" al numero. Ejemplo:

Interno = "14440590"
Externo = "EX14440590"

En cualquier caso, añadir letras a un campo que debería ser número va a limitar mucho las cosas que se pueden hacer con el, así que considérenlo si es posible.

En cuando a la separación, no recomiendo que sea a nivel base de datos. Osea, si así los quieren mostrar, perfecto, pero no los guarden así.
