### ISSUE TITLE
El campo user(profesor) en los grupos debe ser obligatorio

### ISSUE THREAD

**Issue by oswaldoguevara** [davidrochin/sae-ingles#6]
Validar que en la base de datos, y en el código se valide que al crear un nuevo grupo, contenga un profesor obligatoriamente

**Comment by davidrochin** [comment]
Esto fue intencional, ya que a veces se crean grupos y se ponen a asignar alumnos sin saber quien va a terminar siendo el profesor asignado. Checalo y confirmamelo para hacerlo.
